"use client";
import React, { useState, useEffect, useRef } from 'react';
import { Mic, StopCircle, Pause, Trash2, CheckCircle2, Globe, ArrowLeft, Hexagon, ChevronDown, Save, Loader2, Play, X, Download, FileText, User, Type, UploadCloud, Database } from 'lucide-react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import axios from 'axios';
import api from '../../../../utils/api'; // might need this if we still want to save to db
import jsPDF from 'jspdf';
import * as pdfjsLib from 'pdfjs-dist';
import mammoth from 'mammoth';
import Tesseract from 'tesseract.js';

if (typeof window !== 'undefined') {
  pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.min.js`;
}

export default function VoiceCapturePage() {
  const [isRecording, setIsRecording] = useState(false);
  const [isPaused, setIsPaused] = useState(false);
  const [transcript, setTranscript] = useState('');
  const [recognition, setRecognition] = useState<any>(null);
  const [recordingTime, setRecordingTime] = useState(0);
  const [language, setLanguage] = useState('en-US');
  const [toastMessage, setToastMessage] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [role, setRole] = useState('intern');
  const [activeTab, setActiveTab] = useState<'voice' | 'text' | 'files' | 'records'>('voice');
  const [manualText, setManualText] = useState('');
  const [isProcessingFile, setIsProcessingFile] = useState(false);
  const [fileProgress, setFileProgress] = useState({ text: '', percent: 0 });
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [detectedCategory, setDetectedCategory] = useState<string>('General');
  const [detectedTags, setDetectedTags] = useState<string[]>([]);
  const transcriptRef = useRef(transcript);
  const categoryRef = useRef(detectedCategory);
  const tagsRef = useRef(detectedTags);
  const [recentLogs, setRecentLogs] = useState<any[]>([]);
  const [selectedRecord, setSelectedRecord] = useState<any>(null);

  const downloadPDF = () => {
    if (!selectedRecord) return;
    const doc = new jsPDF();
    
    // Header Background
    doc.setFillColor(15, 31, 46); // Dark Blue Header
    doc.rect(0, 0, 210, 40, 'F');
    
    // Header Text
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text("WorkSync Official Record", 15, 25);
    
    // Metadata Block
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Date:", 15, 55);
    doc.setFont("helvetica", "normal");
    doc.text(new Date(selectedRecord.createdAt).toLocaleString(), 45, 55);
    
    doc.setFont("helvetica", "bold");
    doc.text("Category:", 15, 65);
    doc.setFont("helvetica", "normal");
    doc.text(selectedRecord.category || 'General', 45, 65);

    doc.setFont("helvetica", "bold");
    doc.text("Tags:", 15, 75);
    doc.setFont("helvetica", "normal");
    doc.text(selectedRecord.tags || 'None', 45, 75);
    
    // Separator line
    doc.setDrawColor(200, 200, 200);
    doc.line(15, 85, 195, 85);
    
    // Transcript Header
    doc.setTextColor(30, 30, 30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Transcript Details", 15, 98);
    
    // Transcript Content
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    
    const splitText = doc.splitTextToSize(selectedRecord.textContent || '', 180);
    doc.text(splitText, 15, 110);
    
    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.text(`Generated by AI WorkSync Platform - Page ${i}`, 105, 290, { align: "center" });
    }
    
    doc.save(`WorkLog_${selectedRecord.id || 'export'}.pdf`);
  };

  const downloadWord = () => {
    if (!selectedRecord) return;
    const header = "<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>Record</title><style>body { font-family: 'Segoe UI', Arial, sans-serif; color: #333; line-height: 1.6; } .header { background-color: #0F1F2E; color: white; padding: 25px; text-align: center; } .metadata { margin: 25px 20px; padding: 20px; border: 1px solid #e0e0e0; background-color: #fafafa; border-radius: 8px; } .content { margin: 20px; } h1 { margin: 0; font-size: 26px; font-weight: normal; } h2 { color: #0F1F2E; border-bottom: 2px solid #C7F23A; padding-bottom: 8px; margin-bottom: 20px; } .tag { display: inline-block; background-color: #e2e8f0; color: #475569; padding: 4px 10px; border-radius: 12px; font-size: 13px; margin-right: 8px; font-weight: bold; } .footer { text-align: center; font-size: 12px; color: #94a3b8; margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 15px; }</style></head><body>";
    const footer = "</body></html>";
    const tagsHtml = (selectedRecord.tags || '').split(',').map((t: string) => t.trim() ? `<span class="tag">${t}</span>` : '').join('');
    
    const htmlContent = `
      <div class="header">
        <h1>WorkSync Official Record</h1>
      </div>
      <div class="metadata">
        <p><strong>Date:</strong> ${new Date(selectedRecord.createdAt).toLocaleString()}</p>
        <p><strong>Category:</strong> ${selectedRecord.category || 'General'}</p>
        <p><strong>Tags:</strong> ${tagsHtml || 'None'}</p>
      </div>
      <div class="content">
        <h2>Transcript Details</h2>
        <p>${(selectedRecord.textContent || '').replace(/\n/g, '<br>')}</p>
      </div>
      <div class="footer">
        Generated by AI WorkSync Platform
      </div>
    `;
    const sourceHTML = header + htmlContent + footer;
    
    const source = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(sourceHTML);
    const fileDownload = document.createElement("a");
    document.body.appendChild(fileDownload);
    fileDownload.href = source;
    fileDownload.download = `WorkLog_${selectedRecord.id || 'export'}.doc`;
    fileDownload.click();
    document.body.removeChild(fileDownload);
  };

  useEffect(() => {
    categoryRef.current = detectedCategory;
    tagsRef.current = detectedTags;
  }, [detectedCategory, detectedTags]);

  useEffect(() => {
    fetchRecentLogs();
  }, []);

  const fetchRecentLogs = async () => {
    const token = localStorage.getItem('token');
    if (!token) return;
    try {
      const res = await api.get('/worklogs?limit=50');
      setRecentLogs(res.data.data || res.data || []);
    } catch (err) {
      console.error("Failed to fetch recent logs", err);
    }
  };

  useEffect(() => {
    transcriptRef.current = transcript;
  }, [transcript]);

  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (isRecording && !isPaused) {
      interval = setInterval(() => {
        setRecordingTime(prev => prev + 1);
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [isRecording, isPaused]);

  useEffect(() => {
    // Basic Rule-based AI Categorization
    const t = transcript.toLowerCase();
    const rules = [
      { category: 'Website Development', keywords: ['website', 'web application', 'frontend', 'backend', 'react', 'nextjs', 'ui', 'ux', 'landing page'] },
      { category: 'Mobile Application Development', keywords: ['mobile app', 'android', 'ios', 'flutter', 'react native', 'apk'] },
      { category: 'Technical Support', keywords: ['troubleshooting', 'support', 'issue fixed', 'installation', 'configuration', 'maintenance'] },
      { category: 'Debugging', keywords: ['bug', 'debug', 'error', 'fix', 'issue resolved'] },
      { category: 'Meeting', keywords: ['meeting', 'discussion', 'client call', 'review', 'presentation'] },
      { category: 'Infrastructure Management', keywords: ['dns', 'server', 'network', 'firewall', 'google workspace', 'microsoft 365'] },
      { category: 'AI & Innovation', keywords: ['ai', 'machine learning', 'automation', 'chatbot', 'innovation'] }
    ];

    let cat = "Waiting...";
    let tags: string[] = [];

    if (t.length >= 5) {
      cat = "General";
      
      const scores: { category: string; count: number; matched: string[] }[] = [];
      for (const rule of rules) {
        let count = 0;
        const matched: string[] = [];
        for (const kw of rule.keywords) {
          if (t.includes(kw.toLowerCase())) {
            count++;
            matched.push(kw);
          }
        }
        if (count > 0) scores.push({ category: rule.category, count, matched });
      }

      if (scores.length > 0) {
        scores.sort((a, b) => b.count - a.count);
        cat = scores[0].category;
        
        const allKeywords = new Set<string>();
        scores.forEach(s => s.matched.forEach(kw => allKeywords.add(kw)));
        tags = Array.from(allKeywords).map(kw => `#${kw.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('')}`);
      }
    }

    setDetectedCategory(cat);
    setDetectedTags(tags);
  }, [transcript]);

  const toggleRecording = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      alert("Speech Recognition not supported in this browser.");
      return;
    }

    if (isRecording) {
      if (recognition) {
        try { recognition.stop(); } catch (e) { }
      }
      return;
    }

    setTranscript('');
    transcriptRef.current = '';
    setRecordingTime(0);
    setIsRecording(true);
    setIsPaused(false);

    const rec = new SpeechRecognition();
    rec.continuous = true;
    rec.interimResults = true;
    rec.lang = language;

    rec.onresult = (event: any) => {
      let currentTranscript = '';
      for (let i = 0; i < event.results.length; i++) {
        currentTranscript += event.results[i][0].transcript;
      }
      setTranscript(currentTranscript);
    };

    rec.onend = () => {
      setIsRecording(false);
      if (transcriptRef.current.trim()) {
        autoSaveLog(transcriptRef.current);
      }
    };

    rec.onerror = (event: any) => {
      console.error("Speech recognition error:", event.error);
      setIsRecording(false);
      setIsPaused(false);
    };

    setRecognition(rec);
    try { rec.start(); } catch (e) { setIsRecording(false); setIsPaused(false); }
  };

  const togglePause = () => {
    if (!isRecording) return;
    setIsPaused(!isPaused);
    if (!isPaused) {
      if (recognition) { try { recognition.stop(); } catch (e) {} }
    } else {
      try { recognition.start(); } catch (e) {}
    }
  };

  const autoSaveLog = async (finalTranscript: string) => {
    if (!finalTranscript.trim()) return;
    setIsSaving(true);
    try {
      let textToSave = finalTranscript;
      
      if (language === 'ta-IN') {
        setToastMessage('Translating to English...');
        try {
          const res = await axios.get(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(finalTranscript)}&langpair=ta|en`);
          if (res.data && res.data.responseData && res.data.responseData.translatedText) {
            textToSave = res.data.responseData.translatedText;
          }
        } catch (translateError) {
          console.error('Translation failed', translateError);
        }
      }

      // We wrap the API call in a try/catch specifically for auth errors
      // If the user isn't logged in, we'll just show a success message but it won't be in the DB.
      // Better yet, just skip saving if no token.
      const token = localStorage.getItem('token');
      if (token) {
        const categoryToSave = categoryRef.current !== 'Waiting...' ? categoryRef.current : 'General';
        const tagsToSave = [...tagsRef.current, role].join(",");
        await api.post('/worklogs', {
          textContent: textToSave,
          category: categoryToSave,
          tags: tagsToSave,
          organizationId: null,
          projectId: null,
        });
      }
      
      setToastMessage('Transcript captured successfully!');
      setTimeout(() => setToastMessage(''), 3000);
      fetchRecentLogs();
      
    } catch (error) {
      console.error('Failed to auto-save worklog', error);
      setToastMessage('Transcript captured! (Login to sync to cloud)');
      setTimeout(() => setToastMessage(''), 4000);
    } finally {
      setIsSaving(false);
    }
  };

  const processFile = async (file: File) => {
    setIsProcessingFile(true);
    setFileProgress({ text: `Analyzing ${file.name}...`, percent: 10 });
    
    try {
      let extractedText = '';
      
      if (file.type === 'application/pdf') {
        setFileProgress({ text: 'Extracting text from PDF...', percent: 30 });
        const arrayBuffer = await file.arrayBuffer();
        const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
        let fullText = '';
        for (let i = 1; i <= pdf.numPages; i++) {
          setFileProgress({ text: `Reading PDF page ${i} of ${pdf.numPages}...`, percent: 30 + Math.floor((i / pdf.numPages) * 40) });
          const page = await pdf.getPage(i);
          const content = await page.getTextContent();
          const strings = content.items.map((item: any) => item.str);
          fullText += strings.join(' ') + '\n';
        }
        extractedText = fullText;
        
      } else if (file.name.endsWith('.docx') || file.name.endsWith('.doc')) {
        if (file.name.endsWith('.doc')) {
          throw new Error('The older .doc format is not supported. Please save your file as a newer .docx file and try again.');
        }
        setFileProgress({ text: 'Reading Word Document...', percent: 50 });
        const arrayBuffer = await file.arrayBuffer();
        const result = await mammoth.extractRawText({ arrayBuffer });
        extractedText = result.value;
        
      } else if (file.type.startsWith('image/')) {
        setFileProgress({ text: 'Running Optical Character Recognition (OCR)...', percent: 20 });
        const worker = await Tesseract.createWorker('eng', 1, {
          logger: (m: any) => {
            if (m.status === 'recognizing text') {
              setFileProgress({ text: `OCR Progress: ${Math.round(m.progress * 100)}%`, percent: 20 + (m.progress * 60) });
            }
          }
        });
        const { data: { text } } = await worker.recognize(file);
        extractedText = text;
        await worker.terminate();
        
      } else if (file.type.startsWith('audio/') || file.name.endsWith('.wav') || file.name.endsWith('.mp3') || file.name.endsWith('.ogg')) {
        setFileProgress({ text: 'Loading Local AI Audio Model (Whisper)...', percent: 10 });
        const { pipeline, env } = await import('@xenova/transformers');
        env.allowLocalModels = false;
        env.useBrowserCache = true;
        
        const transcriber = await pipeline('automatic-speech-recognition', 'Xenova/whisper-tiny', {
          progress_callback: (progress: any) => {
            if (progress.status === 'downloading') {
              setFileProgress({ text: `Downloading AI Model: ${Math.round(progress.progress)}%`, percent: 10 + (progress.progress * 0.4) });
            }
          }
        });

        setFileProgress({ text: 'Decoding Audio Data...', percent: 60 });
        const arrayBuffer = await file.arrayBuffer();
        const audioContext = new (window.AudioContext || (window as any).webkitAudioContext)({ sampleRate: 16000 });
        const audioBuffer = await audioContext.decodeAudioData(arrayBuffer);
        const audioData = audioBuffer.getChannelData(0);

        setFileProgress({ text: 'Transcribing Audio (this may take a moment)...', percent: 80 });
        const result = await transcriber(audioData);
        extractedText = Array.isArray(result) ? result.map(r => r.text).join(' ') : (result as any).text;
      } else if (file.type.startsWith('text/')) {
        setFileProgress({ text: 'Reading Text File...', percent: 50 });
        extractedText = await file.text();
      } else {
        throw new Error('Unsupported file format.');
      }
      
      setFileProgress({ text: 'Finalizing extraction...', percent: 90 });
      if (!extractedText.trim()) throw new Error('No text could be extracted from this file.');
      
      setFileProgress({ text: 'Saving Record...', percent: 100 });
      await autoSaveLog(extractedText);
      
    } catch (error: any) {
      console.error(error);
      alert('Error processing file: ' + error.message);
    } finally {
      setIsProcessingFile(false);
      setFileProgress({ text: '', percent: 0 });
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault();
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      processFile(e.target.files[0]);
    }
  };

  const clearRecording = () => {
    if (recognition && isRecording) {
      try { recognition.stop(); } catch (e) { }
    }
    setIsRecording(false);
    setIsPaused(false);
    setTranscript('');
    setRecordingTime(0);
  };

  const formatTime = (seconds: number) => {
    const hrs = Math.floor(seconds / 3600);
    const mins = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;
    return `${hrs.toString().padStart(2, '0')}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const visualizerBars = Array.from({ length: 40 }).map((_, i) => {
    const height = (isRecording && !isPaused) ? Math.random() * 100 : 10;
    return <div key={i} className={`w-1 bg-opti-lime/80 rounded-full transition-all duration-75`} style={{ height: `${height}%` }}></div>
  });

  return (
    <div className="h-[calc(100vh-140px)] bg-[#071420] text-white font-inter flex flex-col overflow-hidden rounded-2xl border border-white/5">
      
      {/* Toast */}
      <AnimatePresence>
        {toastMessage && (
          <motion.div 
            initial={{ opacity: 0, y: -20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -20, scale: 0.95 }}
            className="fixed top-6 right-6 z-50 flex items-center gap-3 bg-[#0F1F2E] border border-white/10 px-5 py-3.5 rounded-xl shadow-2xl"
          >
            <CheckCircle2 className="w-5 h-5 text-[#C7F23A]" />
            <p className="text-sm font-bold text-white">{toastMessage}</p>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="px-8 mt-6">
        <div className="flex flex-wrap items-center gap-2 border-b border-white/10 pb-4">
          <button 
            onClick={() => setActiveTab('voice')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-all ${activeTab === 'voice' ? 'bg-opti-lime text-[#071420]' : 'text-gray-400 hover:text-white hover:bg-white/5'}`}
          >
            <Mic size={16} /> Voice Capture
          </button>
          <button 
            onClick={() => setActiveTab('text')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-all ${activeTab === 'text' ? 'bg-opti-lime text-[#071420]' : 'text-gray-400 hover:text-white hover:bg-white/5'}`}
          >
            <Type size={16} /> Text Input
          </button>
          <button 
            onClick={() => setActiveTab('files')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-all ${activeTab === 'files' ? 'bg-opti-lime text-[#071420]' : 'text-gray-400 hover:text-white hover:bg-white/5'}`}
          >
            <UploadCloud size={16} /> Files Upload
          </button>
          <button 
            onClick={() => setActiveTab('records')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-all ${activeTab === 'records' ? 'bg-opti-lime text-[#071420]' : 'text-gray-400 hover:text-white hover:bg-white/5'}`}
          >
            <Database size={16} /> All Records (Worklogs)
          </button>
        </div>
      </div>

      <main className="flex-1 flex flex-col xl:flex-row p-8 gap-8 max-w-[1600px] mx-auto w-full min-h-0 overflow-hidden">
        
        {activeTab === 'voice' && (
          <>
            {/* Left Side - Recording */}
            <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col flex-1 shadow-2xl overflow-y-auto custom-scrollbar">
              <div className="flex justify-between items-center mb-6">
                <h2 className="text-sm sm:text-base md:text-xl font-bold whitespace-nowrap">Record Your Voice</h2>
                {isRecording && (
                  <div className="flex items-center gap-3 text-sm font-bold text-opti-lime">
                    <div className="w-3 h-8 flex items-center gap-1">
                      <div className="w-1 h-3 bg-opti-lime animate-pulse rounded-full"></div>
                      <div className="w-1 h-2 bg-opti-lime animate-pulse rounded-full" style={{ animationDelay: '0.2s' }}></div>
                      <div className="w-1 h-4 bg-opti-lime animate-pulse rounded-full" style={{ animationDelay: '0.4s' }}></div>
                    </div>
                    Listening...
                  </div>
                )}
              </div>
              
              <div className="flex-1 flex flex-col items-center justify-center relative min-h-0">
                <button 
                  onClick={toggleRecording}
                  className={`relative w-32 h-32 rounded-full flex items-center justify-center transition-all duration-300 ${isRecording ? 'bg-[#071420] text-opti-lime shadow-[0_0_50px_rgba(199,242,58,0.2)]' : 'bg-[#071420] text-gray-400 hover:text-opti-lime hover:shadow-[0_0_30px_rgba(199,242,58,0.1)]'}`}
                >
                  {isRecording && (
                    <div className="absolute inset-0 rounded-full border-2 border-opti-lime opacity-50 animate-ping"></div>
                  )}
                  <div className={`absolute inset-2 rounded-full border border-opti-lime/20 ${isRecording ? 'opacity-100' : 'opacity-0'}`}></div>
                  <Mic className="w-16 h-16 relative z-10" />
                </button>
                
                <div className="text-center mt-6">
                  <div className="text-4xl font-mono font-bold">{formatTime(recordingTime)}</div>
                  <div className="text-sm text-gray-400 mt-2">
                    {!isRecording ? 'Ready to record' : isPaused ? 'Paused' : 'Recording in progress'}
                  </div>
                </div>
                
                <div className="w-full h-12 mt-6 flex items-end justify-center gap-1 px-8">
                  {visualizerBars}
                </div>
              </div>
              
              <div className="grid grid-cols-3 gap-3 mt-6">
                <button onClick={togglePause} disabled={!isRecording} className="flex items-center justify-center py-4 rounded-xl border border-yellow-500/30 bg-yellow-500/10 hover:bg-yellow-500/20 text-yellow-500 transition-colors disabled:opacity-50 disabled:cursor-not-allowed">
                  {isPaused ? <Play className="w-6 h-6" /> : <Pause className="w-6 h-6" />}
                </button>
                <button onClick={toggleRecording} className={`flex items-center justify-center py-4 rounded-xl border ${isRecording ? 'border-red-500/30 bg-red-500/10 hover:bg-red-500/20 text-red-500' : 'border-opti-lime/30 bg-opti-lime/10 hover:bg-opti-lime/20 text-opti-lime'} transition-colors`}>
                  {isRecording ? <StopCircle className="w-6 h-6" /> : <Mic className="w-6 h-6" />}
                </button>
                <button onClick={clearRecording} className="flex items-center justify-center py-4 rounded-xl bg-white/5 hover:bg-white/10 text-gray-400 hover:text-white transition-colors">
                  <Trash2 className="w-6 h-6" />
                </button>
              </div>
            </div>

            {/* Right Side - Transcript */}
            <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col flex-1 shadow-2xl">
              <div className="flex justify-between items-center mb-6">
                <h2 className="text-sm sm:text-base md:text-xl font-bold flex items-center gap-1.5 whitespace-nowrap">
                  Live Transcription 
                  {isRecording && <span className="text-[9px] md:text-[10px] uppercase tracking-wider bg-[#1C3E2F] text-opti-lime px-1.5 py-0.5 rounded font-bold">Live</span>}
                </h2>
                <div className="flex items-center gap-1.5 md:gap-2 bg-[#071420] border border-white/10 rounded-lg px-2 py-1 md:px-3 md:py-1.5 shadow-sm">
                  <Globe className="w-3.5 h-3.5 md:w-4 md:h-4 text-opti-lime" /> 
                  <select 
                    value={language}
                    onChange={(e) => setLanguage(e.target.value)}
                    className="bg-transparent text-white text-xs md:text-sm font-bold focus:outline-none cursor-pointer"
                  >
                    <option value="en-US" className="bg-[#0F1F2E]">English (US)</option>
                    <option value="ta-IN" className="bg-[#0F1F2E]">Tamil (தமிழ்)</option>
                  </select>
                </div>
              </div>
              
              <div className="flex-1 bg-[#071420] border border-white/5 rounded-2xl p-6 relative overflow-hidden flex flex-col shadow-inner">
                <div className="flex-1 overflow-y-auto text-gray-300 leading-relaxed text-lg font-inter custom-scrollbar pr-4">
                  {transcript || <span className="text-gray-600 italic">Press the microphone icon and start speaking to see transcription here...</span>}
                  {isRecording && <span className="w-2 h-5 ml-1 inline-block bg-opti-lime animate-pulse align-middle"></span>}
                </div>
              </div>
              
              <div className="mt-6 flex justify-between items-center">
                <div className="text-sm text-gray-500">{transcript.length} / 5000 characters</div>
                <Link href="/dashboard" className="px-6 py-3 bg-white/10 hover:bg-white/20 rounded-xl text-sm font-bold transition-colors">
                  Go to Dashboard →
                </Link>
              </div>
            </div>
          </>
        )}

        {activeTab === 'text' && (
          <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col flex-1 shadow-2xl">
             <div className="flex justify-between items-center mb-6">
               <h2 className="text-sm sm:text-base md:text-xl font-bold whitespace-nowrap">Manual Text Input</h2>
               <div className="flex items-center gap-3">
                 <div className="flex items-center gap-2 bg-[#071420] border border-white/10 rounded-lg px-3 py-1.5 shadow-sm">
                   <Globe className="w-4 h-4 text-opti-lime" /> 
                   <select 
                     value={language}
                     onChange={(e) => setLanguage(e.target.value)}
                     className="bg-transparent text-white text-sm font-bold focus:outline-none cursor-pointer"
                   >
                     <option value="en-US" className="bg-[#0F1F2E]">English (US)</option>
                     <option value="ta-IN" className="bg-[#0F1F2E]">Tamil (தமிழ்)</option>
                   </select>
                 </div>
               </div>
             </div>
             <textarea 
               value={manualText}
               onChange={(e) => setManualText(e.target.value)}
               className="flex-1 bg-[#071420] border border-white/5 rounded-2xl p-6 text-white resize-none custom-scrollbar focus:outline-none focus:border-opti-lime transition-colors" 
               placeholder="Type or paste your worklog details here... WorkSync AI will automatically categorize and tag it upon saving."
             ></textarea>
             <div className="flex justify-end gap-3 mt-6">
               <button 
                 onClick={() => setManualText('')}
                 disabled={!manualText.trim()}
                 className="py-4 bg-white/5 text-gray-400 hover:text-white hover:bg-white/10 rounded-xl text-sm font-bold flex items-center justify-center gap-2 w-32 transition-all disabled:opacity-50"
               >
                 <Trash2 size={18} /> Clear
               </button>
               <button 
                 onClick={() => {
                   autoSaveLog(manualText);
                   setManualText('');
                 }}
                 disabled={!manualText.trim() || isSaving}
                 className="py-4 bg-opti-lime text-[#071420] rounded-xl text-sm font-bold flex items-center justify-center gap-2 w-48 hover:scale-[1.02] transition-transform disabled:opacity-50"
               >
                 {isSaving ? <Loader2 className="w-5 h-5 animate-spin" /> : <Save size={18} />} 
                 {isSaving ? 'Saving...' : 'Save Record'}
               </button>
             </div>
          </div>
        )}

        {activeTab === 'files' && (
          <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col flex-1 shadow-2xl">
             <div className="flex justify-between items-center mb-6">
               <h2 className="text-sm sm:text-base md:text-xl font-bold whitespace-nowrap">Files Upload</h2>
               <div className="flex items-center gap-3">
                 <div className="flex items-center gap-2 bg-[#071420] border border-white/10 rounded-lg px-3 py-1.5 shadow-sm">
                   <Globe className="w-4 h-4 text-opti-lime" /> 
                   <select 
                     value={language}
                     onChange={(e) => setLanguage(e.target.value)}
                     disabled={isProcessingFile}
                     className="bg-transparent text-white text-sm font-bold focus:outline-none cursor-pointer disabled:opacity-50"
                   >
                     <option value="en-US" className="bg-[#0F1F2E]">English (US)</option>
                     <option value="ta-IN" className="bg-[#0F1F2E]">Tamil (தமிழ்)</option>
                   </select>
                 </div>
               </div>
             </div>

            <div 
              className={`flex-1 border-2 border-dashed ${isProcessingFile ? 'border-opti-lime/50 bg-opti-lime/5' : 'border-white/20 hover:border-opti-lime/50'} rounded-3xl p-8 flex flex-col shadow-inner items-center justify-center text-center transition-colors relative bg-[#071420]`}
              onDragOver={handleDragOver}
              onDrop={handleDrop}
            >
              <input 
              type="file" 
              ref={fileInputRef} 
              className="hidden" 
              accept=".pdf,.doc,.docx,.txt,.png,.jpg,.jpeg,.mp3,.wav,.ogg" 
              onChange={handleFileSelect} 
            />
            
            {isProcessingFile ? (
              <div className="w-full max-w-md flex flex-col items-center">
                <Loader2 className="w-16 h-16 text-opti-lime animate-spin mb-6" />
                <h2 className="text-2xl font-bold mb-3">Processing File...</h2>
                <p className="text-gray-400 mb-6">{fileProgress.text}</p>
                <div className="w-full h-3 bg-[#071420] rounded-full overflow-hidden border border-white/10">
                  <div className="h-full bg-opti-lime transition-all duration-300" style={{ width: `${fileProgress.percent}%` }}></div>
                </div>
              </div>
            ) : (
              <>
                <UploadCloud size={64} className="text-gray-600 mb-6" />
                <h2 className="text-2xl font-bold mb-3">Upload Work Documents</h2>
                <p className="text-gray-400 mb-8 max-w-md">Drag and drop documents (PDF, Word), images (OCR), or audio files here. WorkSync AI will automatically extract text, analyze content, and securely store it as a tagged worklog.</p>
                <button 
                  onClick={() => fileInputRef.current?.click()}
                  className="py-4 px-8 bg-opti-lime text-[#071420] rounded-xl text-sm font-bold flex items-center justify-center gap-2 hover:scale-[1.02] transition-transform"
                >
                   <UploadCloud size={18} /> Browse Files
                </button>
              </>
            )}
          </div>
          </div>
        )}

        {activeTab === 'records' && (
          <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col flex-1 shadow-2xl">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-xl font-bold">All Records (Worklogs)</h2>
              <div className="text-sm text-gray-500">Total Records: {recentLogs.length}</div>
            </div>
            
            <div className="flex-1 overflow-y-auto custom-scrollbar pr-4 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 pb-8 content-start">
              {recentLogs.length === 0 ? (
                 <div className="col-span-full text-center text-gray-500 py-10 italic">No records found.</div>
              ) : (
                recentLogs.map((log, idx) => (
                  <div 
                    key={log.id || idx} 
                    onClick={() => setSelectedRecord(log)}
                    className="flex flex-col gap-3 bg-[#071420] border border-white/5 rounded-xl p-5 hover:border-white/20 transition-all group cursor-pointer hover:-translate-y-1 hover:shadow-lg"
                  >
                    <div className="flex justify-between items-start gap-2">
                      <div className="text-sm font-bold text-white leading-snug line-clamp-3 flex-1">{log.textContent}</div>
                      <button className="w-8 h-8 rounded-full bg-[#1C3E2F] flex items-center justify-center shrink-0 border border-opti-lime/20 text-opti-lime">
                        <Play className="w-3.5 h-3.5 ml-0.5" />
                      </button>
                    </div>
                    <div className="mt-auto pt-3 border-t border-white/5 flex flex-wrap items-center gap-2 text-[10px] text-gray-500">
                      <span>{new Date(log.createdAt).toLocaleDateString()}</span>
                      {log.category && (
                        <span className="bg-white/10 px-1.5 py-0.5 rounded text-white">{log.category}</span>
                      )}
                      {log.tags && log.tags.split(',').slice(0, 3).map((tag: string, i: number) => tag.trim() ? (
                        <span key={i} className="bg-opti-lime/10 text-opti-lime border border-opti-lime/20 px-1.5 py-0.5 rounded font-bold">{tag.trim()}</span>
                      ) : null)}
                      {log.tags && log.tags.split(',').length > 3 && (
                        <span className="text-gray-500">+{log.tags.split(',').length - 3}</span>
                      )}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        )}

        {/* Right Side Sidebar - Saved Records (Only show when not in full records view) */}
        {activeTab !== 'records' && (
        <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col w-full xl:w-[450px] shrink-0 shadow-2xl">
          <h2 className="text-xl font-bold mb-6">Saved Records</h2>
          
          <div className="flex-1 space-y-4 overflow-y-auto custom-scrollbar pr-2 pb-4">
            {recentLogs.length === 0 ? (
               <div className="text-sm text-gray-500 py-4 italic text-center">No recent logs found. Login to sync records.</div>
            ) : (
              recentLogs.map((log, idx) => (
                <div 
                  key={log.id || idx} 
                  onClick={() => setSelectedRecord(log)}
                  className="flex flex-col gap-2 bg-[#071420] border border-white/5 rounded-xl p-4 hover:border-white/10 transition-colors group cursor-pointer"
                >
                  <div className="flex items-start gap-4">
                    <button className="w-8 h-8 rounded-full bg-[#1C3E2F] flex items-center justify-center shrink-0 border border-opti-lime/20 text-opti-lime group-hover:scale-110 transition-transform">
                      <Play className="w-3.5 h-3.5 ml-0.5" />
                    </button>
                    <div className="flex-1 min-w-0">
                      <div className="text-sm font-bold text-white leading-snug mb-2">{log.textContent?.substring(0, 60) || 'Voice Capture'}...</div>
                      <div className="flex flex-wrap items-center gap-2 text-[10px] text-gray-500">
                        <span>{new Date(log.createdAt).toLocaleDateString()}</span>
                        {log.category && (
                          <span className="bg-white/10 px-1.5 py-0.5 rounded text-white">{log.category}</span>
                        )}
                        {log.tags && log.tags.split(',').map((tag: string, i: number) => tag.trim() ? (
                          <span key={i} className="bg-opti-lime/10 text-opti-lime border border-opti-lime/20 px-1.5 py-0.5 rounded font-bold">{tag.trim()}</span>
                        ) : null)}
                      </div>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
          
          <div className="mt-4 pt-4 border-t border-white/5 text-xs text-gray-500">
            Showing latest {recentLogs.length} records
          </div>
        </div>

        )}

      </main>

      {/* Modal Popup for Record */}
      <AnimatePresence>
        {selectedRecord && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
            <motion.div 
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="bg-[#0F1F2E] border border-white/10 rounded-3xl w-full max-w-2xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden"
            >
              <div className="flex justify-between items-center p-6 border-b border-white/10">
                <h2 className="text-2xl font-bold">Record Details</h2>
                <button onClick={() => setSelectedRecord(null)} className="p-2 bg-white/5 hover:bg-white/10 rounded-full text-gray-400 hover:text-white transition-colors">
                  <X size={20} />
                </button>
              </div>
              
              <div className="p-6 overflow-y-auto custom-scrollbar flex-1 space-y-6">
                <div className="flex flex-wrap gap-4 text-sm">
                  <div className="bg-[#071420] px-4 py-2 rounded-xl border border-white/5">
                    <span className="text-gray-500 block text-xs mb-1">Date</span>
                    <span className="font-bold">{new Date(selectedRecord.createdAt).toLocaleDateString()}</span>
                  </div>
                  <div className="bg-[#071420] px-4 py-2 rounded-xl border border-white/5">
                    <span className="text-gray-500 block text-xs mb-1">Category</span>
                    <span className="font-bold text-opti-lime">{selectedRecord.category || 'General'}</span>
                  </div>
                </div>
                
                {selectedRecord.tags && (
                  <div className="flex flex-wrap gap-2">
                    {selectedRecord.tags.split(',').map((tag: string, i: number) => tag.trim() ? (
                      <span key={i} className="bg-opti-lime/10 text-opti-lime border border-opti-lime/20 px-2 py-1 rounded text-xs font-bold">{tag.trim()}</span>
                    ) : null)}
                  </div>
                )}
                
                <div>
                  <h3 className="text-sm font-bold text-gray-400 mb-3">Transcript</h3>
                  <div className="bg-[#071420] border border-white/5 rounded-2xl p-5 text-gray-300 leading-relaxed text-base whitespace-pre-wrap">
                    {selectedRecord.textContent}
                  </div>
                </div>
              </div>
              
              <div className="p-6 border-t border-white/10 flex flex-wrap gap-4 bg-[#071420]">
                <button onClick={downloadPDF} className="flex-1 flex items-center justify-center gap-2 py-3 bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/20 rounded-xl font-bold transition-colors">
                  <FileText size={18} /> Download as PDF
                </button>
                <button onClick={downloadWord} className="flex-1 flex items-center justify-center gap-2 py-3 bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 border border-blue-500/20 rounded-xl font-bold transition-colors">
                  <Download size={18} /> Download as Word
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
