"use client";
import React, { useState, useEffect, useRef } from 'react';
import { Mic, StopCircle, Pause, Trash2, CheckCircle2, Globe, ArrowLeft, Hexagon, ChevronDown, Save, Loader2, Play, X, Download, FileText, User, Type, UploadCloud, Database, Edit3, Plus, Calendar, Clock } from 'lucide-react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import axios from 'axios';
import api from '../../utils/api'; // might need this if we still want to save to db
import jsPDF from 'jspdf';
import * as pdfjsLib from 'pdfjs-dist';
import mammoth from 'mammoth';
import Tesseract from 'tesseract.js';

if (typeof window !== 'undefined') {
  pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.min.js`;
}

export default function VoiceCapturePage() {
  const [isRecording, setIsRecording] = useState(false);
  const [isPaused, setIsPaused] = useState(false);
  const [transcript, setTranscript] = useState('');
  const [recognition, setRecognition] = useState<any>(null);
  const [recordingTime, setRecordingTime] = useState(0);
  const [language, setLanguage] = useState('en-US');
  const [toastMessage, setToastMessage] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [role, setRole] = useState('intern');
  const [showProfile, setShowProfile] = useState(false);
  const [userEmail, setUserEmail] = useState('');
  const [userName, setUserName] = useState('');
  const [activeTab, setActiveTab] = useState<'voice' | 'text' | 'files' | 'records'>('voice');
  const [manualText, setManualText] = useState('');
  const [isProcessingFile, setIsProcessingFile] = useState(false);
  const [fileProgress, setFileProgress] = useState({ text: '', percent: 0 });
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [detectedCategory, setDetectedCategory] = useState<string>('General');
  const [detectedTags, setDetectedTags] = useState<string[]>([]);
  const transcriptRef = useRef(transcript);
  const categoryRef = useRef(detectedCategory);
  const tagsRef = useRef(detectedTags);
  const [recentLogs, setRecentLogs] = useState<any[]>([]);
  const [selectedRecord, setSelectedRecord] = useState<any>(null);
  const [isEditingRecord, setIsEditingRecord] = useState(false);
  const [editRecordText, setEditRecordText] = useState('');

  const downloadPDF = () => {
    if (!selectedRecord) return;
    const doc = new jsPDF();
    
    // Full Page Background
    doc.setFillColor(255, 255, 255); // White Background
    doc.rect(0, 0, 210, 297, 'F'); // A4 size is 210x297
    
    // Header Background
    doc.setFillColor(15, 31, 46); // Dark Blue Header
    doc.rect(0, 0, 210, 40, 'F');
    
    // Header Text
    doc.setTextColor(255, 255, 255); // White
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text(`WorkSync ${userName || 'Official'} Record`, 15, 25);
    
    // Metadata Block
    doc.setTextColor(100, 100, 100); // Gray labels
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Date:", 15, 55);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30); // Dark text
    doc.text(new Date(selectedRecord.createdAt).toLocaleString(), 45, 55);
    
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "bold");
    doc.text("Category:", 15, 65);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30); 
    doc.text(selectedRecord.category || 'General', 45, 65);

    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "bold");
    doc.text("Tags:", 15, 75);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    doc.text(selectedRecord.tags || 'None', 45, 75);
    
    // Separator line
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.line(15, 85, 195, 85);
    
    // Transcript Header
    doc.setTextColor(15, 31, 46); // Dark Blue
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Transcript Details", 15, 98);
    
    // Transcript Content
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(50, 50, 50); // Dark Gray
    
    const splitText = doc.splitTextToSize(selectedRecord.textContent || '', 180);
    doc.text(splitText, 15, 110);
    
    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.text(`Generated by AI WorkSync Platform - Page ${i}`, 105, 290, { align: "center" });
    }
    
    doc.save(`WorkLog_${selectedRecord.id || 'export'}.pdf`);
  };

  const downloadWord = () => {
    if (!selectedRecord) return;
    const header = "<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>Record</title><style>body { font-family: 'Segoe UI', Arial, sans-serif; background-color: #ffffff; color: #333333; line-height: 1.6; } .header { background-color: #0F1F2E; color: #ffffff; padding: 25px; text-align: center; border-bottom: 2px solid #e2e8f0; } .metadata { margin: 25px 20px; padding: 20px; border: 1px solid #e2e8f0; background-color: #f8fafc; border-radius: 8px; } .content { margin: 20px; } h1 { margin: 0; font-size: 26px; font-weight: bold; } h2 { color: #0F1F2E; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-bottom: 20px; } .tag { display: inline-block; background-color: #e2e8f0; color: #475569; padding: 4px 10px; border-radius: 12px; font-size: 13px; margin-right: 8px; font-weight: bold; border: 1px solid #cbd5e1; } .footer { text-align: center; font-size: 12px; color: #64748b; margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 15px; } strong { color: #475569; }</style></head><body>";
    const footer = "</body></html>";
    const tagsHtml = (selectedRecord.tags || '').split(',').map((t: string) => t.trim() ? `<span class="tag">${t}</span>` : '').join('');
    
    const htmlContent = `
      <div class="header">
        <h1>WorkSync ${userName || 'Official'} Record</h1>
      </div>
      <div class="metadata">
        <p><strong>Date:</strong> ${new Date(selectedRecord.createdAt).toLocaleString()}</p>
        <p><strong>Category:</strong> ${selectedRecord.category || 'General'}</p>
        <p><strong>Tags:</strong> ${tagsHtml || 'None'}</p>
      </div>
      <div class="content">
        <h2>Transcript Details</h2>
        <p>${(selectedRecord.textContent || '').replace(/\n/g, '<br>')}</p>
      </div>
      <div class="footer">
        Generated by AI WorkSync Platform
      </div>
    `;
    const sourceHTML = header + htmlContent + footer;
    
    const source = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(sourceHTML);
    const fileDownload = document.createElement("a");
    document.body.appendChild(fileDownload);
    fileDownload.href = source;
    fileDownload.download = `WorkLog_${selectedRecord.id || 'export'}.doc`;
    fileDownload.click();
    document.body.removeChild(fileDownload);
  };

  useEffect(() => {
    categoryRef.current = detectedCategory;
    tagsRef.current = detectedTags;
  }, [detectedCategory, detectedTags]);

  useEffect(() => {
    if (selectedRecord) {
      setIsEditingRecord(false);
      setEditRecordText(selectedRecord.textContent || '');
    }
  }, [selectedRecord]);

  const handleDeleteRecord = () => {
    if (!selectedRecord) return;
    let updatedLogs = recentLogs;
    if (selectedRecord.id?.startsWith('FullDay_')) {
      const dateString = new Date(selectedRecord.createdAt).toLocaleDateString();
      updatedLogs = recentLogs.filter(log => new Date(log.createdAt).toLocaleDateString() !== dateString);
    } else {
      updatedLogs = recentLogs.filter(log => log.id !== selectedRecord.id);
    }
    setRecentLogs(updatedLogs);
    localStorage.setItem('mock_worklogs', JSON.stringify(updatedLogs));
    setSelectedRecord(null);
  };

  const handleSaveEdit = () => {
    if (!selectedRecord) return;
    let updatedLogs = recentLogs;
    if (selectedRecord.id?.startsWith('FullDay_')) {
      const dateString = new Date(selectedRecord.createdAt).toLocaleDateString();
      // Remove all logs from this date
      updatedLogs = recentLogs.filter(log => new Date(log.createdAt).toLocaleDateString() !== dateString);
      // Create a single consolidated log
      const newLog = {
        id: Date.now().toString(),
        createdAt: selectedRecord.createdAt,
        category: selectedRecord.category,
        tags: selectedRecord.tags,
        textContent: editRecordText
      };
      updatedLogs = [newLog, ...updatedLogs].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
    } else {
      updatedLogs = recentLogs.map(log => 
        log.id === selectedRecord.id ? { ...log, textContent: editRecordText } : log
      );
    }
    setRecentLogs(updatedLogs);
    localStorage.setItem('mock_worklogs', JSON.stringify(updatedLogs));
    setSelectedRecord({ ...selectedRecord, textContent: editRecordText });
    setIsEditingRecord(false);
  };

  useEffect(() => {
    let localName = '';
    try {
      const userStr = localStorage.getItem('user');
      if (userStr) {
        const user = JSON.parse(userStr);
        if (user.role) setRole(user.role);
        if (user.email) setUserEmail(user.email);
        if (user.name) {
          setUserName(user.name);
          localName = user.name;
        }
      }
    } catch (e) {}
    fetchRecentLogs(localName);
  }, []);

  const fetchRecentLogs = async (nameFilter?: string) => {
    const token = localStorage.getItem('token');
    if (!token) return;
    const currentName = nameFilter || userName;
    try {
      const res = await api.get('/worklogs?limit=50');
      setRecentLogs(res.data.data || res.data || []);
    } catch (err) {
      console.error("Failed to fetch recent logs from API, loading local mock data.", err);
      const localLogs = JSON.parse(localStorage.getItem('mock_worklogs') || '[]');
      const filteredLogs = currentName 
        ? localLogs.filter((log: any) => log.userName === currentName)
        : localLogs;
      setRecentLogs(filteredLogs);
    }
  };

  useEffect(() => {
    transcriptRef.current = transcript;
  }, [transcript]);

  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (isRecording && !isPaused) {
      interval = setInterval(() => {
        setRecordingTime(prev => prev + 1);
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [isRecording, isPaused]);

  useEffect(() => {
    // Basic Rule-based AI Categorization
    const t = transcript.toLowerCase();
    const rules = [
      { category: 'Website Development', keywords: ['website', 'web application', 'frontend', 'backend', 'react', 'nextjs', 'ui', 'ux', 'landing page'] },
      { category: 'Mobile Application Development', keywords: ['mobile app', 'android', 'ios', 'flutter', 'react native', 'apk'] },
      { category: 'Technical Support', keywords: ['troubleshooting', 'support', 'issue fixed', 'installation', 'configuration', 'maintenance'] },
      { category: 'Debugging', keywords: ['bug', 'debug', 'error', 'fix', 'issue resolved'] },
      { category: 'Meeting', keywords: ['meeting', 'discussion', 'client call', 'review', 'presentation'] },
      { category: 'Infrastructure Management', keywords: ['dns', 'server', 'network', 'firewall', 'google workspace', 'microsoft 365'] },
      { category: 'AI & Innovation', keywords: ['ai', 'machine learning', 'automation', 'chatbot', 'innovation'] }
    ];

    let cat = "Waiting...";
    let tags: string[] = [];

    if (t.length >= 5) {
      cat = "General";
      
      const scores: { category: string; count: number; matched: string[] }[] = [];
      for (const rule of rules) {
        let count = 0;
        const matched: string[] = [];
        for (const kw of rule.keywords) {
          if (t.includes(kw.toLowerCase())) {
            count++;
            matched.push(kw);
          }
        }
        if (count > 0) scores.push({ category: rule.category, count, matched });
      }

      if (scores.length > 0) {
        scores.sort((a, b) => b.count - a.count);
        cat = scores[0].category;
        
        const allKeywords = new Set<string>();
        scores.forEach(s => s.matched.forEach(kw => allKeywords.add(kw)));
        tags = Array.from(allKeywords).map(kw => `#${kw.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('')}`);
      }
    }

    setDetectedCategory(cat);
    setDetectedTags(tags);
  }, [transcript]);

  const toggleRecording = () => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      alert("Speech Recognition not supported in this browser.");
      return;
    }

    if (isRecording) {
      if (recognition) {
        try { recognition.stop(); } catch (e) { }
      }
      return;
    }

    setTranscript('');
    transcriptRef.current = '';
    setRecordingTime(0);
    setIsRecording(true);
    setIsPaused(false);

    const rec = new SpeechRecognition();
    rec.continuous = true;
    rec.interimResults = true;
    rec.lang = language;

    rec.onresult = (event: any) => {
      let currentTranscript = '';
      for (let i = 0; i < event.results.length; i++) {
        currentTranscript += event.results[i][0].transcript;
      }
      setTranscript(currentTranscript);
    };

    rec.onend = () => {
      setIsRecording(false);
      if (transcriptRef.current.trim()) {
        autoSaveLog(transcriptRef.current);
      }
    };

    rec.onerror = (event: any) => {
      console.error("Speech recognition error:", event.error);
      setIsRecording(false);
      setIsPaused(false);
    };

    setRecognition(rec);
    try { rec.start(); } catch (e) { setIsRecording(false); setIsPaused(false); }
  };

  const togglePause = () => {
    if (!isRecording) return;
    setIsPaused(!isPaused);
    if (!isPaused) {
      if (recognition) { try { recognition.stop(); } catch (e) {} }
    } else {
      try { recognition.start(); } catch (e) {}
    }
  };

  const autoSaveLog = async (finalTranscript: string) => {
    if (!finalTranscript.trim()) return;
    setIsSaving(true);
    try {
      let textToSave = finalTranscript;
      
      if (language === 'ta-IN') {
        setToastMessage('Translating to English...');
        try {
          const res = await axios.get(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(finalTranscript)}&langpair=ta|en`);
          if (res.data && res.data.responseData && res.data.responseData.translatedText) {
            textToSave = res.data.responseData.translatedText;
          }
        } catch (translateError) {
          console.error('Translation failed', translateError);
        }
      }

      const token = localStorage.getItem('token');
      if (token) {
        const categoryToSave = categoryRef.current !== 'Waiting...' ? categoryRef.current : 'General';
        const tagsToSave = [...tagsRef.current, role].join(",");
        
        try {
          await api.post('/worklogs', {
            textContent: textToSave,
            category: categoryToSave,
            tags: tagsToSave,
            organizationId: null,
            projectId: null,
          });
        } catch (apiError) {
          console.warn('API error, saving to local mock storage instead.', apiError);
          const localLogs = JSON.parse(localStorage.getItem('mock_worklogs') || '[]');
          localLogs.unshift({
            id: Date.now().toString(),
            textContent: textToSave,
            category: categoryToSave,
            tags: tagsToSave,
            createdAt: new Date().toISOString(),
            userName: userName,
            role: role
          });
          localStorage.setItem('mock_worklogs', JSON.stringify(localLogs));
        }
      }
      
      setToastMessage('Transcript captured successfully!');
      setTimeout(() => setToastMessage(''), 3000);
      fetchRecentLogs();
      
    } catch (error) {
      console.error('Failed to auto-save worklog', error);
      setToastMessage('Transcript captured! (Login to sync to cloud)');
      setTimeout(() => setToastMessage(''), 4000);
    } finally {
      setIsSaving(false);
    }
  };

  const processFile = async (file: File) => {
    setIsProcessingFile(true);
    setFileProgress({ text: `Analyzing ${file.name}...`, percent: 10 });
    
    try {
      let extractedText = '';
      
      if (file.type === 'application/pdf') {
        setFileProgress({ text: 'Extracting text from PDF...', percent: 30 });
        const arrayBuffer = await file.arrayBuffer();
        const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
        let fullText = '';
        for (let i = 1; i <= pdf.numPages; i++) {
          setFileProgress({ text: `Reading PDF page ${i} of ${pdf.numPages}...`, percent: 30 + Math.floor((i / pdf.numPages) * 40) });
          const page = await pdf.getPage(i);
          const content = await page.getTextContent();
          const strings = content.items.map((item: any) => item.str);
          fullText += strings.join(' ') + '\n';
        }
        extractedText = fullText;
        
      } else if (file.name.endsWith('.docx') || file.name.endsWith('.doc')) {
        if (file.name.endsWith('.doc')) {
          throw new Error('The older .doc format is not supported. Please save your file as a newer .docx file and try again.');
        }
        setFileProgress({ text: 'Reading Word Document...', percent: 50 });
        const arrayBuffer = await file.arrayBuffer();
        const result = await mammoth.extractRawText({ arrayBuffer });
        extractedText = result.value;
        
      } else if (file.type.startsWith('image/')) {
        setFileProgress({ text: 'Running Optical Character Recognition (OCR)...', percent: 20 });
        const worker = await Tesseract.createWorker({
          logger: m => {
            if (m.status === 'recognizing text') {
              setFileProgress({ text: `OCR Progress: ${Math.round(m.progress * 100)}%`, percent: 20 + (m.progress * 60) });
            }
          }
        });
        await worker.loadLanguage('eng');
        await worker.initialize('eng');
        const { data: { text } } = await worker.recognize(file);
        extractedText = text;
        await worker.terminate();
        
      } else if (file.type.startsWith('audio/') || file.name.endsWith('.wav') || file.name.endsWith('.mp3') || file.name.endsWith('.ogg')) {
        setFileProgress({ text: 'Loading Local AI Audio Model (Whisper)...', percent: 10 });
        const { pipeline, env } = await import('@xenova/transformers');
        env.allowLocalModels = false;
        env.useBrowserCache = true;
        
        const transcriber = await pipeline('automatic-speech-recognition', 'Xenova/whisper-tiny', {
          progress_callback: (progress: any) => {
            if (progress.status === 'downloading') {
              setFileProgress({ text: `Downloading AI Model: ${Math.round(progress.progress)}%`, percent: 10 + (progress.progress * 0.4) });
            }
          }
        });

        setFileProgress({ text: 'Decoding Audio Data...', percent: 60 });
        const arrayBuffer = await file.arrayBuffer();
        const audioContext = new (window.AudioContext || (window as any).webkitAudioContext)({ sampleRate: 16000 });
        const audioBuffer = await audioContext.decodeAudioData(arrayBuffer);
        const audioData = audioBuffer.getChannelData(0);

        setFileProgress({ text: 'Transcribing Audio (this may take a moment)...', percent: 80 });
        const result = await transcriber(audioData);
        extractedText = Array.isArray(result) ? result.map(r => r.text).join(' ') : (result as any).text;
      } else if (file.type.startsWith('text/')) {
        setFileProgress({ text: 'Reading Text File...', percent: 50 });
        extractedText = await file.text();
      } else {
        throw new Error('Unsupported file format.');
      }
      
      setFileProgress({ text: 'Finalizing extraction...', percent: 90 });
      if (!extractedText.trim()) throw new Error('No text could be extracted from this file.');
      
      setFileProgress({ text: 'Saving Record...', percent: 100 });
      await autoSaveLog(extractedText);
      
    } catch (error: any) {
      console.error(error);
      alert('Error processing file: ' + error.message);
    } finally {
      setIsProcessingFile(false);
      setFileProgress({ text: '', percent: 0 });
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault();
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      processFile(e.target.files[0]);
    }
  };

  const clearRecording = () => {
    if (recognition && isRecording) {
      try { recognition.stop(); } catch (e) { }
    }
    setIsRecording(false);
    setIsPaused(false);
    setTranscript('');
    setRecordingTime(0);
  };

  const formatTime = (seconds: number) => {
    const hrs = Math.floor(seconds / 3600);
    const mins = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;
    return `${hrs.toString().padStart(2, '0')}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const visualizerBars = Array.from({ length: 40 }).map((_, i) => {
    const height = (isRecording && !isPaused) ? Math.random() * 100 : 10;
    return <div key={i} className={`w-1 bg-opti-lime/80 rounded-full transition-all duration-75`} style={{ height: `${height}%` }}></div>
  });

  const groupedLogs = recentLogs.reduce((acc: any, log: any) => {
    const d = new Date(log.createdAt);
    const dateStr = `${d.toLocaleDateString()}|${d.toLocaleDateString(undefined, { weekday: 'long' })}`;
    if (!acc[dateStr]) acc[dateStr] = [];
    acc[dateStr].push(log);
    return acc;
  }, {});

  const handleFullDaySelect = (date: string, logs: any[]) => {
    const combinedText = logs.map(log => 
      `[${new Date(log.createdAt).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}] ${log.textContent}`
    ).join('\n');

    const allTags = Array.from(new Set(logs.flatMap(l => l.tags ? l.tags.split(',').map((t: string) => t.trim()) : []).filter(Boolean))).join(', ');
    const allCategories = Array.from(new Set(logs.map(l => l.category).filter(Boolean))).join(', ') || 'General';

    setSelectedRecord({
      id: `FullDay_${date.replace(/\//g, '-')}`,
      createdAt: logs[0].createdAt,
      category: allCategories,
      tags: allTags,
      textContent: combinedText
    });
  };

  return (
    <div className="h-screen bg-[#071420] text-white font-inter flex flex-col overflow-hidden">
      
      {/* Profile Modal */}
      <AnimatePresence>
        {showProfile && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm"
            onClick={() => setShowProfile(false)}
          >
            <motion.div 
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-[#0F1F2E] border border-white/10 rounded-2xl p-8 max-w-sm w-full shadow-2xl relative"
              onClick={e => e.stopPropagation()}
            >
              <button 
                onClick={() => setShowProfile(false)}
                className="absolute top-4 right-4 text-gray-400 hover:text-white"
              >
                <X size={20} />
              </button>
              
              <div className="flex flex-col items-center text-center">
                <div className="w-20 h-20 bg-opti-lime/10 rounded-full flex items-center justify-center mb-4 border border-opti-lime/30">
                  <User size={40} className="text-opti-lime" />
                </div>
                <h3 className="text-2xl font-bold text-white mb-1">{userName || 'My Profile'}</h3>
                <div className="w-12 h-1 bg-opti-lime rounded-full mb-6"></div>
                
                <div className="w-full bg-[#071420] rounded-xl p-4 space-y-4 text-left border border-white/5">
                  <div>
                    <label className="text-xs text-gray-500 uppercase font-bold tracking-wider">Full Name</label>
                    <div className="text-white text-sm mt-1 truncate capitalize">{userName || 'User'}</div>
                  </div>
                  <div>
                    <label className="text-xs text-gray-500 uppercase font-bold tracking-wider">Email Address</label>
                    <div className="text-white text-sm mt-1 truncate">{userEmail || 'user@example.com'}</div>
                  </div>
                  <div>
                    <label className="text-xs text-gray-500 uppercase font-bold tracking-wider">Account Role</label>
                    <div className="text-opti-lime text-sm mt-1 font-semibold capitalize">{(role || 'intern').replace('_', ' ')}</div>
                  </div>
                </div>
                
                <button 
                  onClick={() => {
                    localStorage.removeItem('token');
                    localStorage.removeItem('user');
                    window.location.href = '/login';
                  }}
                  className="mt-6 w-full py-3 rounded-xl bg-red-500/10 text-red-500 hover:bg-red-500/20 font-bold transition-colors border border-red-500/20"
                >
                  Sign Out
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Toast */}
      <AnimatePresence>
        {toastMessage && (
          <motion.div 
            initial={{ opacity: 0, y: -20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -20, scale: 0.95 }}
            className="fixed top-6 right-6 z-50 flex items-center gap-3 bg-[#0F1F2E] border border-white/10 px-5 py-3.5 rounded-xl shadow-2xl"
          >
            <CheckCircle2 className="w-5 h-5 text-[#C7F23A]" />
            <p className="text-sm font-bold text-white">{toastMessage}</p>
          </motion.div>
        )}
      </AnimatePresence>

      <header className="h-auto md:h-20 py-4 md:py-0 border-b border-white/10 px-4 md:px-8 flex flex-col md:flex-row items-center justify-between gap-4 md:gap-0">
        <Link href="/" className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors w-full md:w-auto justify-between md:justify-start">
          <div className="flex items-center gap-2 text-xl font-bold md:hidden text-white">
            <Hexagon className="text-opti-lime" size={28} />
            <span>WorkSync</span>
          </div>
          <div className="flex items-center gap-2 text-sm md:text-base">
            <ArrowLeft size={16} className="md:w-5 md:h-5" /> <span className="hidden md:inline">Back to Home</span>
          </div>
        </Link>
        <div className="hidden md:flex items-center gap-2 text-xl font-bold absolute left-1/2 -translate-x-1/2">
          <Hexagon className="text-opti-lime" size={28} />
          <span>WorkSync Engine</span>
        </div>
        <div className="w-full md:w-24 flex justify-center md:justify-end">
          <button onClick={() => setShowProfile(true)} className="flex items-center justify-center w-10 h-10 rounded-full bg-white/5 hover:bg-white/10 transition-colors border border-white/10">
            <User size={18} className="text-opti-lime" />
          </button>
        </div>
      </header>

      <div className="px-4 md:px-8 mt-6">
        <div className="flex overflow-x-auto [&::-webkit-scrollbar]:hidden items-center gap-2 border-b border-white/10 pb-4">
          <button 
            onClick={() => setActiveTab('voice')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-all whitespace-nowrap ${activeTab === 'voice' ? 'bg-opti-lime text-[#071420]' : 'text-gray-400 hover:text-white hover:bg-white/5'}`}
          >
            <Mic size={16} /> Voice Capture
          </button>
          <button 
            onClick={() => setActiveTab('text')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-all whitespace-nowrap ${activeTab === 'text' ? 'bg-opti-lime text-[#071420]' : 'text-gray-400 hover:text-white hover:bg-white/5'}`}
          >
            <Type size={16} /> Text Input
          </button>
          <button 
            onClick={() => setActiveTab('files')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-all whitespace-nowrap ${activeTab === 'files' ? 'bg-opti-lime text-[#071420]' : 'text-gray-400 hover:text-white hover:bg-white/5'}`}
          >
            <UploadCloud size={16} /> Files Upload
          </button>
          <button 
            onClick={() => setActiveTab('records')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-all whitespace-nowrap ${activeTab === 'records' ? 'bg-opti-lime text-[#071420]' : 'text-gray-400 hover:text-white hover:bg-white/5'}`}
          >
            <Database size={16} /> All Records (Worklogs)
          </button>
        </div>
      </div>

      <main className="flex-1 flex flex-col xl:flex-row p-8 gap-8 max-w-[1600px] mx-auto w-full min-h-0 overflow-hidden">
        
        {activeTab === 'voice' && (
          <>
            {/* Left Side - Recording */}
            <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col flex-1 shadow-2xl overflow-y-auto custom-scrollbar">
              <div className="flex justify-between items-center mb-6">
                <h2 className="text-xl font-bold">Record Your Voice</h2>
                {isRecording && (
                  <div className="flex items-center gap-3 text-sm font-bold text-opti-lime">
                    <div className="w-3 h-8 flex items-center gap-1">
                      <div className="w-1 h-3 bg-opti-lime animate-pulse rounded-full"></div>
                      <div className="w-1 h-2 bg-opti-lime animate-pulse rounded-full" style={{ animationDelay: '0.2s' }}></div>
                      <div className="w-1 h-4 bg-opti-lime animate-pulse rounded-full" style={{ animationDelay: '0.4s' }}></div>
                    </div>
                    Listening...
                  </div>
                )}
              </div>
              
              <div className="flex-1 flex flex-col items-center justify-center relative min-h-0">
                <button 
                  onClick={toggleRecording}
                  className={`relative w-32 h-32 rounded-full flex items-center justify-center transition-all duration-300 ${isRecording ? 'bg-[#071420] text-opti-lime shadow-[0_0_50px_rgba(199,242,58,0.2)]' : 'bg-[#071420] text-gray-400 hover:text-opti-lime hover:shadow-[0_0_30px_rgba(199,242,58,0.1)]'}`}
                >
                  {isRecording && (
                    <div className="absolute inset-0 rounded-full border-2 border-opti-lime opacity-50 animate-ping"></div>
                  )}
                  <div className={`absolute inset-2 rounded-full border border-opti-lime/20 ${isRecording ? 'opacity-100' : 'opacity-0'}`}></div>
                  <Mic className="w-16 h-16 relative z-10" />
                </button>
                
                <div className="text-center mt-6">
                  <div className="text-4xl font-mono font-bold">{formatTime(recordingTime)}</div>
                  <div className="text-sm text-gray-400 mt-2">
                    {!isRecording ? 'Ready to record' : isPaused ? 'Paused' : 'Recording in progress'}
                  </div>
                </div>
                
                <div className="w-full h-12 mt-6 flex items-end justify-center gap-1 px-8">
                  {visualizerBars}
                </div>
              </div>
              
              <div className="grid grid-cols-3 gap-3 mt-6">
                <button onClick={togglePause} disabled={!isRecording} className="flex items-center justify-center py-4 rounded-xl border border-yellow-500/30 bg-yellow-500/10 hover:bg-yellow-500/20 text-yellow-500 transition-colors disabled:opacity-50 disabled:cursor-not-allowed">
                  {isPaused ? <Play className="w-6 h-6" /> : <Pause className="w-6 h-6" />}
                </button>
                <button onClick={toggleRecording} className={`flex items-center justify-center py-4 rounded-xl border ${isRecording ? 'border-red-500/30 bg-red-500/10 hover:bg-red-500/20 text-red-500' : 'border-opti-lime/30 bg-opti-lime/10 hover:bg-opti-lime/20 text-opti-lime'} transition-colors`}>
                  {isRecording ? <StopCircle className="w-6 h-6" /> : <Mic className="w-6 h-6" />}
                </button>
                <button onClick={clearRecording} className="flex items-center justify-center py-4 rounded-xl bg-white/5 hover:bg-white/10 text-gray-400 hover:text-white transition-colors">
                  <Trash2 className="w-6 h-6" />
                </button>
              </div>
            </div>

            {/* Right Side - Transcript */}
            <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col flex-1 shadow-2xl">
              <div className="flex justify-between items-center mb-6">
                <h2 className="text-xl font-bold flex items-center gap-3">
                  Live Transcription 
                  {isRecording && <span className="text-[10px] uppercase tracking-wider bg-[#1C3E2F] text-opti-lime px-2 py-0.5 rounded font-bold">Live</span>}
                </h2>
                <div className="flex items-center gap-3">


                  <div className="flex items-center gap-2 bg-[#071420] border border-white/10 rounded-lg px-3 py-1.5 shadow-sm">
                    <Globe className="w-4 h-4 text-opti-lime" /> 
                    <select 
                      value={language}
                      onChange={(e) => setLanguage(e.target.value)}
                      disabled={isRecording}
                      className="bg-transparent text-white text-sm font-bold focus:outline-none cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      <option value="en-US" className="bg-[#0F1F2E]">English (US)</option>
                      <option value="ta-IN" className="bg-[#0F1F2E]">Tamil (தமிழ்)</option>
                    </select>
                  </div>
                </div>
              </div>
              
              <div className="flex-1 bg-[#071420] border border-white/5 rounded-2xl p-6 relative overflow-hidden flex flex-col shadow-inner">
                <div className="flex-1 overflow-y-auto text-gray-300 leading-relaxed text-lg font-inter custom-scrollbar pr-4">
                  {transcript || <span className="text-gray-600 italic">Press the microphone icon and start speaking to see transcription here...</span>}
                  {isRecording && <span className="w-2 h-5 ml-1 inline-block bg-opti-lime animate-pulse align-middle"></span>}
                </div>
              </div>
              
              <div className="mt-6 flex justify-between items-center">
                <div className="text-sm text-gray-500">{transcript.length} / 5000 characters</div>
              </div>
            </div>
          </>
        )}

        {activeTab === 'text' && (
          <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col flex-1 shadow-2xl">
             <div className="flex justify-between items-center mb-6">
               <h2 className="text-xl font-bold">Manual Text Input</h2>
               <div className="flex items-center gap-3">


                 <div className="flex items-center gap-2 bg-[#071420] border border-white/10 rounded-lg px-3 py-1.5 shadow-sm">
                   <Globe className="w-4 h-4 text-opti-lime" /> 
                   <select 
                     value={language}
                     onChange={(e) => setLanguage(e.target.value)}
                     className="bg-transparent text-white text-sm font-bold focus:outline-none cursor-pointer"
                   >
                     <option value="en-US" className="bg-[#0F1F2E]">English (US)</option>
                     <option value="ta-IN" className="bg-[#0F1F2E]">Tamil (தமிழ்)</option>
                   </select>
                 </div>
               </div>
             </div>
             <textarea 
               value={manualText}
               onChange={(e) => setManualText(e.target.value)}
               className="flex-1 bg-[#071420] border border-white/5 rounded-2xl p-6 text-white resize-none custom-scrollbar focus:outline-none focus:border-opti-lime transition-colors" 
               placeholder="Type or paste your worklog details here... WorkSync AI will automatically categorize and tag it upon saving."
             ></textarea>
             <div className="flex justify-end gap-3 mt-6">
               <button 
                 onClick={() => setManualText('')}
                 disabled={!manualText.trim()}
                 className="py-4 bg-white/5 text-gray-400 hover:text-white hover:bg-white/10 rounded-xl text-sm font-bold flex items-center justify-center gap-2 w-32 transition-all disabled:opacity-50"
               >
                 <Trash2 size={18} /> Clear
               </button>
               <button 
                 onClick={() => {
                   autoSaveLog(manualText);
                   setManualText('');
                 }}
                 disabled={!manualText.trim() || isSaving}
                 className="py-4 bg-opti-lime text-[#071420] rounded-xl text-sm font-bold flex items-center justify-center gap-2 w-48 hover:scale-[1.02] transition-transform disabled:opacity-50"
               >
                 {isSaving ? <Loader2 className="w-5 h-5 animate-spin" /> : <Save size={18} />} 
                 {isSaving ? 'Saving...' : 'Save Record'}
               </button>
             </div>
          </div>
        )}

        {activeTab === 'files' && (
          <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col flex-1 shadow-2xl">
             <div className="flex justify-between items-center mb-6">
               <h2 className="text-xl font-bold">Files Upload</h2>
               <div className="flex items-center gap-3">


                 <div className="flex items-center gap-2 bg-[#071420] border border-white/10 rounded-lg px-3 py-1.5 shadow-sm">
                   <Globe className="w-4 h-4 text-opti-lime" /> 
                   <select 
                     value={language}
                     onChange={(e) => setLanguage(e.target.value)}
                     disabled={isProcessingFile}
                     className="bg-transparent text-white text-sm font-bold focus:outline-none cursor-pointer disabled:opacity-50"
                   >
                     <option value="en-US" className="bg-[#0F1F2E]">English (US)</option>
                     <option value="ta-IN" className="bg-[#0F1F2E]">Tamil (தமிழ்)</option>
                   </select>
                 </div>
               </div>
             </div>

            <div 
              className={`flex-1 border-2 border-dashed ${isProcessingFile ? 'border-opti-lime/50 bg-opti-lime/5' : 'border-white/20 hover:border-opti-lime/50'} rounded-3xl p-8 flex flex-col shadow-inner items-center justify-center text-center transition-colors relative bg-[#071420]`}
              onDragOver={handleDragOver}
              onDrop={handleDrop}
            >
              <input 
              type="file" 
              ref={fileInputRef} 
              className="hidden" 
              accept=".pdf,.doc,.docx,.txt,.png,.jpg,.jpeg,.mp3,.wav,.ogg" 
              onChange={handleFileSelect} 
            />
            
            {isProcessingFile ? (
              <div className="w-full max-w-md flex flex-col items-center">
                <Loader2 className="w-16 h-16 text-opti-lime animate-spin mb-6" />
                <h2 className="text-2xl font-bold mb-3">Processing File...</h2>
                <p className="text-gray-400 mb-6">{fileProgress.text}</p>
                <div className="w-full h-3 bg-[#071420] rounded-full overflow-hidden border border-white/10">
                  <div className="h-full bg-opti-lime transition-all duration-300" style={{ width: `${fileProgress.percent}%` }}></div>
                </div>
              </div>
            ) : (
              <>
                <UploadCloud size={64} className="text-gray-600 mb-6" />
                <h2 className="text-2xl font-bold mb-3">Upload Work Documents</h2>
                <p className="text-gray-400 mb-8 max-w-md">Drag and drop documents (PDF, Word), images (OCR), or audio files here. WorkSync AI will automatically extract text, analyze content, and securely store it as a tagged worklog.</p>
                <button 
                  onClick={() => fileInputRef.current?.click()}
                  className="py-4 px-8 bg-opti-lime text-[#071420] rounded-xl text-sm font-bold flex items-center justify-center gap-2 hover:scale-[1.02] transition-transform"
                >
                   <UploadCloud size={18} /> Browse Files
                </button>
              </>
            )}
          </div>
          </div>
        )}

        {activeTab === 'records' && (
          <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col flex-1 shadow-2xl">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-xl font-bold">All Records (Worklogs)</h2>
              <div className="text-sm text-gray-500">Total Records: {recentLogs.length}</div>
            </div>
            
            <div className="flex-1 overflow-y-auto custom-scrollbar pr-4 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 pb-8 content-start">
              {Object.keys(groupedLogs).length === 0 ? (
                 <div className="col-span-full text-center text-gray-500 py-10 italic">No records found.</div>
              ) : (
                Object.keys(groupedLogs).map((date) => (
                  <div 
                    key={date} 
                    className="col-span-full bg-[#071420] border border-white/5 rounded-2xl p-6 shadow-inner mb-2 cursor-pointer hover:border-opti-lime/30 transition-colors group"
                    onClick={() => handleFullDaySelect(date, groupedLogs[date])}
                  >
                    <div className="flex items-center justify-between mb-4 border-b border-white/5 pb-3">
                      <h3 className="text-opti-lime font-bold text-lg flex items-center gap-2">
                        {date.includes('|') ? (
                          <>
                            <Calendar size={18} /> {date.split('|')[0]}
                            <span className="text-opti-lime/50 mx-2">•</span> {date.split('|')[1]}
                          </>
                        ) : (
                          <><Hexagon size={18} /> {date}</>
                        )}
                      </h3>
                      <button 
                        onClick={(e) => { e.stopPropagation(); handleFullDaySelect(date, groupedLogs[date]); }}
                        className="flex items-center gap-2 text-xs font-bold text-opti-lime bg-opti-lime/10 hover:bg-opti-lime hover:text-[#071420] px-3 py-1.5 rounded-lg transition-all duration-300 cursor-pointer shadow-[0_0_10px_rgba(199,242,58,0)] hover:shadow-[0_0_15px_rgba(199,242,58,0.4)] hover:scale-105 group-hover:bg-opti-lime group-hover:text-[#071420]"
                        title="Download Full Day Record"
                      >
                        <Download size={16} /> Download Day
                      </button>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
                      {groupedLogs[date].map((log: any, idx: number) => (
                        <div 
                          key={log.id || idx} 
                          className="flex flex-col gap-2 p-0 border-l-2 border-opti-lime/50 pl-4"
                        >
                          <div className="flex items-center gap-2 mb-1">
                            <div className="w-2 h-2 rounded-full bg-opti-lime"></div>
                            <span className="text-sm font-bold text-opti-lime">
                              {new Date(log.createdAt).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                            </span>
                            <span className="text-gray-600 text-xs">•</span>
                            {log.category && (
                              <span className="text-[10px] text-gray-400 truncate">{log.category}</span>
                            )}
                          </div>
                          <div className="text-sm text-white leading-snug whitespace-pre-wrap pr-2">{log.textContent}</div>
                          <div className="mt-1 flex flex-wrap items-center gap-2 text-[10px]">
                            {log.tags && log.tags.split(',').slice(0, 3).map((tag: string, i: number) => tag.trim() ? (
                              <span key={i} className="text-opti-lime/60 font-medium">{tag.trim()}</span>
                            ) : null)}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        )}

        {/* Right Side Sidebar - Saved Records (Only show when not in full records view) */}
        {activeTab !== 'records' && (
        <div className="bg-[#0F1F2E] border border-white/5 rounded-3xl p-8 flex flex-col w-full xl:w-[450px] shrink-0 shadow-2xl min-h-0 overflow-y-auto custom-scrollbar">
          <h2 className="text-xl font-bold mb-6">Saved Records</h2>
          
          <div className="flex-1 space-y-6 pr-2 pb-4">
            {Object.keys(groupedLogs).length === 0 ? (
               <div className="text-sm text-gray-500 py-4 italic text-center">No recent logs found.</div>
            ) : (
              Object.keys(groupedLogs).map((date) => (
                <div 
                  key={date} 
                  className="bg-[#071420] border border-white/5 rounded-2xl p-5 shadow-inner cursor-pointer hover:border-opti-lime/30 transition-colors group"
                  onClick={() => handleFullDaySelect(date, groupedLogs[date])}
                >
                  <div className="flex items-center justify-between mb-4 border-b border-white/5 pb-2">
                    <h3 className="text-opti-lime font-bold flex items-center gap-2">
                      {date.includes('|') ? (
                        <>
                          <Calendar size={16} /> {date.split('|')[0]}
                          <span className="text-opti-lime/50 mx-2">•</span> {date.split('|')[1]}
                        </>
                      ) : (
                        <>{date}</>
                      )}
                    </h3>
                    <button 
                      onClick={(e) => { e.stopPropagation(); handleFullDaySelect(date, groupedLogs[date]); }}
                      className="relative flex items-center justify-center w-8 h-8 rounded-full text-opti-lime bg-opti-lime/10 hover:bg-opti-lime hover:text-[#071420] transition-all duration-300 cursor-pointer group-hover:bg-opti-lime group-hover:text-[#071420]"
                      title="Download Full Day Record"
                    >
                      <span className="absolute inset-0 rounded-full border border-opti-lime/50 animate-[ping_2s_ease-in-out_infinite] opacity-75 hidden group-hover:block"></span>
                      <Download size={16} className="relative z-10 transition-transform group-hover:scale-110" />
                    </button>
                  </div>
                  <div className="space-y-4 pt-2">
                    {groupedLogs[date].map((log: any, idx: number) => (
                      <div 
                        key={log.id || idx} 
                        className="relative pl-6 py-1 border-l border-white/10 last:border-transparent"
                      >
                        <div className="absolute left-[-4px] top-2.5 w-2 h-2 rounded-full bg-opti-lime/50"></div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-1.5">
                            <span className="text-xs font-bold text-opti-lime">
                              {new Date(log.createdAt).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                            </span>
                            <span className="text-gray-600 text-[10px]">•</span>
                            {log.category && (
                              <span className="text-[10px] text-gray-400 truncate max-w-[150px]">{log.category}</span>
                            )}
                          </div>
                          <div className="text-sm text-white leading-snug mb-1.5 whitespace-pre-wrap pr-2">{log.textContent || 'Voice Capture'}</div>
                          <div className="flex flex-wrap items-center gap-1.5 text-[10px]">
                            {log.tags && log.tags.split(',').slice(0, 3).map((tag: string, i: number) => tag.trim() ? (
                              <span key={i} className="text-opti-lime/60 font-medium">{tag.trim()}</span>
                            ) : null)}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ))
            )}
          </div>
          
          <div className="mt-4 pt-4 border-t border-white/5 text-xs text-gray-500">
            Showing latest {recentLogs.length} records
          </div>
        </div>

        )}

      </main>

      {/* Modal Popup for Record */}
      <AnimatePresence>
        {selectedRecord && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
            <motion.div 
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="bg-[#0F1F2E] border border-white/10 rounded-3xl w-full max-w-2xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden"
            >
              <div className="flex justify-between items-center p-6 border-b border-white/10">
                <h2 className="text-2xl font-bold">Record Details</h2>
                <button onClick={() => setSelectedRecord(null)} className="p-2 bg-white/5 hover:bg-white/10 rounded-full text-gray-400 hover:text-white transition-colors">
                  <X size={20} />
                </button>
              </div>
              
              <div className="p-6 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none] flex-1 space-y-6">
                <div className="flex flex-wrap gap-4 text-sm">
                  <div className="bg-[#071420] px-4 py-2 rounded-xl border border-white/5">
                    <span className="text-gray-500 block text-xs mb-1">Date</span>
                    <span className="font-bold flex items-center gap-1.5 text-opti-lime"><Calendar size={14} /> {new Date(selectedRecord.createdAt).toLocaleDateString()} <span className="text-opti-lime/50 mx-1">•</span> <span className="text-white">{new Date(selectedRecord.createdAt).toLocaleDateString(undefined, { weekday: 'long' })}</span></span>
                  </div>
                  <div className="bg-[#071420] px-4 py-2 rounded-xl border border-white/5">
                    <span className="text-gray-500 block text-xs mb-1">Category</span>
                    <span className="font-bold text-opti-lime">{selectedRecord.category || 'General'}</span>
                  </div>
                </div>
                
                {selectedRecord.tags && (
                  <div className="flex flex-wrap gap-2">
                    {selectedRecord.tags.split(',').map((tag: string, i: number) => tag.trim() ? (
                      <span key={i} className="bg-opti-lime/10 text-opti-lime border border-opti-lime/20 px-2 py-1 rounded text-xs font-bold">{tag.trim()}</span>
                    ) : null)}
                  </div>
                )}
                
                <div className="flex-1 min-h-0 flex flex-col">
                  <h3 className="text-sm font-bold text-gray-400 mb-3 shrink-0">Transcript</h3>
                  {isEditingRecord ? (
                    <textarea 
                      value={editRecordText}
                      onChange={(e) => setEditRecordText(e.target.value)}
                      className="w-full flex-1 bg-[#071420] border border-opti-lime/50 rounded-2xl p-5 text-gray-300 leading-relaxed text-base focus:outline-none focus:ring-2 focus:ring-opti-lime/50 transition-all min-h-[250px] resize-y"
                    />
                  ) : (
                    <div className="flex-1 bg-[#071420] border border-white/5 rounded-2xl p-5 text-gray-300 leading-relaxed text-base whitespace-pre-wrap">
                      {selectedRecord.textContent}
                    </div>
                  )}
                </div>
              </div>
              
              <div className="p-6 border-t border-white/10 flex flex-wrap gap-4 bg-[#071420]">
                {isEditingRecord ? (
                  <>
                    <button onClick={() => {
                      setEditRecordText(prev => prev + '\n[' + new Date().toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}) + '] ');
                    }} className="flex-1 flex items-center justify-center gap-2 py-3 bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-xl font-bold transition-colors" title="Insert Current Time">
                      <Plus size={18} /> Add Time
                    </button>
                    <button onClick={handleSaveEdit} className="flex-1 flex items-center justify-center gap-2 py-3 bg-opti-lime/10 hover:bg-opti-lime/20 text-opti-lime border border-opti-lime/30 rounded-xl font-bold transition-colors">
                      <Save size={18} /> Save Changes
                    </button>
                  </>
                ) : (
                  <>
                    <button onClick={() => {
                      setEditRecordText(selectedRecord.textContent + '\n[' + new Date().toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}) + '] ');
                      setIsEditingRecord(true);
                    }} className="flex-1 flex items-center justify-center gap-2 py-3 bg-opti-lime/10 hover:bg-opti-lime/20 text-opti-lime border border-opti-lime/30 rounded-xl font-bold transition-colors" title="Add a new entry with current time">
                      <Plus size={18} /> Add
                    </button>
                    <button onClick={() => setIsEditingRecord(true)} className="flex-1 flex items-center justify-center gap-2 py-3 bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-xl font-bold transition-colors">
                      <Edit3 size={18} /> Edit
                    </button>
                  </>
                )}
                <button onClick={handleDeleteRecord} className="flex-1 flex items-center justify-center gap-2 py-3 bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/20 rounded-xl font-bold transition-colors" title="Delete Record">
                  <Trash2 size={18} /> Delete
                </button>
                <div className="w-full flex gap-4 mt-2">
                  <button onClick={downloadPDF} className="flex-1 flex items-center justify-center gap-2 py-3 bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/20 rounded-xl font-bold transition-colors text-sm">
                    <FileText size={16} /> PDF
                  </button>
                  <button onClick={downloadWord} className="flex-1 flex items-center justify-center gap-2 py-3 bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 border border-blue-500/20 rounded-xl font-bold transition-colors text-sm">
                    <Download size={16} /> Word
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
